openapi: 3.0.2

info:
  version: '3.0.0-alpha'
  title: Violet User System Internal APIs
  description: |
    Violet用户授权系统内部API列表，RESTful-Like
  termsOfService: 'https://xmatrix.studio/terms'
  contact:
    name: XMatrix Studio
    url: 'https://oauth.xmatrix.studio/support'
    email: 'a@xmatrix.studio'
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'

servers:
  - url: 'https://oauth.xmatrix.studio/api/v3/i'
    description: XMatrix OAuth APIs

tags:
  - name: User
    description: |
      与用户相关的接口，包括注册、登录、登出、数据、授权等
  - name: Util
    description: |
      工具类接口，包括获取图形验证码等

components:
  # schemas:
  # responses:
  # parameters:
  # examples:
  # requestBodies:
  # headers:
  # securitySchemas:
  # links:
  # callbacks:

paths:
  '/user':
    get:
      tags: [User]
      summary: |
        获取用户信息
    post:
      tags: [User]
      summary: |
        注册账号
      parameters:
        - name: name
          in: query
          description: |
            用户唯一名称<br>
            以字母开头，由字母、数字、下划线、减号组成，最多32位<br>
            /^[a-zA-Z][a-zA-Z0-9_-]{0,31}$/
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,31}$'
        - name: email
          in: query
          description: |
            用户唯一邮箱<br>
            /^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/
          required: true
          schema:
            type: string
            pattern: '^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$'
        - name: password
          in: query
          description: |
            用户密码的SHA512散列值<br>
            密码限制为6-24位，不允许纯数字
          required: true
          schema:
            type: string
        - name: vcode
          in: query
          description: |
            图形验证码
          required: true
          schema:
            type: string
      responses:
        '201':
          description: |
            注册成功
        '400':
          description: |
            注册失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      error_vcode - 图形验证码错误<br>
                      exist_email - 邮箱已存在<br>
                      exist_name - 用户名已存在<br>
                      invalid_email - 非法邮箱<br>
                      invalid_name - 非法用户名<br>
                      invalid_password - 非法密码散列值<br>
                      invalid_vcode - 非法图形验证码<br>
                      not_exist_vcode - 不存在图形验证码记录<br>
                      reserved_name - 用户名保留<br>
                    example: 'exist_name'
    patch:
      tags: [User]
      summary: |
        修改用户个人信息

  '/user/email':
    post:
      tags: [User]
      summary: |
        认证邮箱
    put:
      tags: [User]
      summary: |
        发送邮箱认证邮件

  '/user/session':
    post:
      tags: [User]
      summary: |
        登录账号
    delete:
      tags: [User]
      summary: |
        登出账号

  '/util/vcode':
    get:
      tags: [Util]
      summary: |
        获取图形验证码
      description: |
        用于图形验证码的获取，返回png格式的验证码图形的BASE64字符串，其中验证码为4位数字。<br>
        该接口目前仅用于注册验证。
      responses:
        '200':
          description: |
            获取成功
          content:
            'text/plain':
              schema:
                type: string
              example:
                data:image/png;base64,iVBORw0KGgoAAAAN...
