openapi: 3.0.2

info:
  version: 3.0.0
  title: Violet User Authorization System Internal APIs
  description: Violet用户授权系统内部API列表
  termsOfService: 'https://oauth.xmatrix.studio/terms'
  contact:
    name: XMatrix Studio
    url: 'https://oauth.xmatrix.studio/support'
    email: a@xmatrix.studio
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'

servers:
  - url: 'https://oauth.xmatrix.studio/api/v3/i/'
    description: XMatrix Authorization Service APIs
  - url: 'http://localhost:30001/api/v3/i/'
    description: Localhost Authorization Service APIs

tags:
  - name: Users
    description: 与用户相关的接口，包括注册、登陆、登出等
  - name: Util
    description: 工具类接口，包括获取图形验证码等

paths:
  '/util/captcha':
    get:
      tags: [Util]
      summary: 获取图形验证码
      description: | # TODO
      responses:
        200:
          description: 获取成功
          content:
            'application/json':
              schema:
                type: object
                # TODO
              example:
                # TODO
